#!/usr/bin/env python3
"""build-search.py — generate the full-text search index for the use-case library.

IMPORTANT: this must be RE-RUN after any usecases/*.html page is added or edited,
otherwise the index is stale (verify.sh runs `--check` and fails loudly on drift).

For each usecases/*.html under --root it reads <body data-uc="ID">, strips
<script>/<style> blocks and all tags, decodes entities, lowercases, tokenises
to words, and stores each page as a space-joined sorted unique word list.
Output: <root>/assets/js/search-index.js defining window.UC_SEARCH = {id: "words", ...}.

Usage:
  python3 _extract/build-search.py            # regenerate for the main library
  python3 _extract/build-search.py --root X   # index another edition (e.g. prospect build)
  python3 _extract/build-search.py --check    # exit 1 if on-disk index is stale

Stdlib only. Deterministic output (sorted ids, sorted unique words) so --check
is a pure byte comparison.
"""
import argparse
import html
import json
import re
import sys
from pathlib import Path

LIB_ROOT = Path(__file__).resolve().parent.parent

SCRIPT_STYLE = re.compile(r"<(script|style)\b.*?</\1\s*>", re.I | re.S)
COMMENTS = re.compile(r"<!--.*?-->", re.S)
TAGS = re.compile(r"<[^>]+>")
WORDS = re.compile(r"[a-z0-9][a-z0-9\-]*")
DATA_UC = re.compile(r'<body[^>]*\bdata-uc="([^"]+)"')

HEADER = (
    "/* Generated by _extract/build-search.py — DO NOT EDIT BY HAND.\n"
    "   Re-run `python3 _extract/build-search.py` after any usecases/*.html edit;\n"
    "   verify.sh fails if this file is stale. */\n"
)


def page_words(src):
    txt = SCRIPT_STYLE.sub(" ", src)
    txt = COMMENTS.sub(" ", txt)
    txt = TAGS.sub(" ", txt)
    txt = html.unescape(txt).lower()
    toks = set()
    for w in WORDS.findall(txt):
        w = w.strip("-")
        if w:
            toks.add(w)
    return " ".join(sorted(toks))


def build(root):
    pages = sorted((root / "usecases").glob("*.html"))
    if not pages:
        sys.exit(f"build-search.py: no pages found under {root}/usecases")
    index = {}
    for p in pages:
        src = p.read_text(encoding="utf-8")
        m = DATA_UC.search(src)
        uc_id = m.group(1) if m else p.stem
        if not m:
            print(f"build-search.py: WARNING {p.name} has no data-uc; using filename stem", file=sys.stderr)
        index[uc_id] = page_words(src)
    lines = [HEADER, "window.UC_SEARCH={\n"]
    entries = [f"{json.dumps(k)}:{json.dumps(index[k])}" for k in sorted(index)]
    lines.append(",\n".join(entries))
    lines.append("\n};\n")
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Build assets/js/search-index.js")
    ap.add_argument("--root", default=str(LIB_ROOT),
                    help="library root containing usecases/ and assets/js/ (default: main library)")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the on-disk index differs from what would be generated")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    out = root / "assets" / "js" / "search-index.js"
    content = build(root)
    if args.check:
        on_disk = out.read_text(encoding="utf-8") if out.exists() else None
        if on_disk != content:
            print(f"STALE SEARCH INDEX: {out} does not match usecases/*.html.\n"
                  f"Re-run: python3 _extract/build-search.py" +
                  ("" if root == LIB_ROOT else f" --root {root}"), file=sys.stderr)
            sys.exit(1)
        print(f"OK — search index fresh ({out.relative_to(root)})")
        return
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} ({len(content)} bytes, {content.count(chr(34) + ':')} entries)")


if __name__ == "__main__":
    main()
